spring:
  profiles:
    active: local

# 개발환경 에서만 create-drop 또는 update를 사용하고 운영 환경에서는 validate를 사용한다.
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
